import { Router } from 'express';
import { z } from 'zod';
import { env } from '../lib/env.js';
import { saveAnswer } from '../services/answerStore.js';
import type { ExplainResponse } from '../types/tutor.js';

// Express is the app's single front door. Answers are generated by Jed's Python
// tutor; this route forwards the request unchanged, stores the answer under the
// tutor's own request_id (so /api/voice/start can speak it), and returns the
// tutor's response unchanged, including its provider label.
export const explainRouter = Router();

const answerShape = z.object({
  request_id: z.string().min(1).max(100),
  topic: z.string().nullable().optional(),
  language: z.enum(['bikol_daet', 'tagalog', 'english']),
  explanation: z.string(),
  example: z.string(),
  key_points: z.array(z.string()),
  source_ids: z.array(z.string()).default([]),
  provider: z.string(),
});

export async function fetchTutor(path: string, init: RequestInit = {}): Promise<Response> {
  if (!env.TUTOR_UPSTREAM_URL) throw new Error('TUTOR_UPSTREAM_URL is not set');
  return fetch(`${env.TUTOR_UPSTREAM_URL}${path}`, {
    ...init,
    signal: AbortSignal.timeout(env.TUTOR_TIMEOUT_MS),
  });
}

explainRouter.post('/', async (req, res) => {
  if (!env.TUTOR_UPSTREAM_URL) {
    res.status(503).json({ error: 'Tutor is not configured on the server (TUTOR_UPSTREAM_URL)' });
    return;
  }

  let upstream: Response;
  try {
    upstream = await fetchTutor('/api/explain', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(req.body ?? {}),
    });
  } catch (error) {
    const timedOut = (error as Error).name === 'TimeoutError';
    res.status(timedOut ? 504 : 502).json({
      error: timedOut ? 'The tutor took too long to answer. Please try again.' : 'The tutor service is unreachable.',
    });
    return;
  }

  const text = await upstream.text();
  let body: unknown;
  try {
    body = JSON.parse(text);
  } catch {
    res.status(502).json({ error: 'The tutor returned an invalid response.' });
    return;
  }

  if (upstream.ok) {
    const answer = answerShape.safeParse(body);
    if (answer.success) {
      saveAnswer({ ...answer.data, topic: answer.data.topic ?? null } as ExplainResponse);
    } else {
      console.warn('[explain] tutor answer has an unexpected shape; Listen will not work for it');
    }
  }

  // Pass the tutor's status and body through unchanged (errors are {"error": ...}).
  res.status(upstream.status).json(body);
});
